---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: fedora-kinoite-cachyos

description: Fedora Kinoite minimalista com KDE Plasma e kernel CachyOS.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:

  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages: []

  - type: signing  
